name: parcel CI/CD # название процесса

on:  # отслеживание ветки main
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: # правила для разрешений репозиторий,чтобы не было ошибок при deploy
  id-token: write 
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:  # запуск работы
  build-and-deploy: # название работы
    runs-on: ubuntu-latest 

    strategy: # позволяет создать переменные
      matrix: 
        node-version: [18.x] # стабильная версия js

    steps: # шаги  
      - uses: actions/checkout@v3 #проверки для работы git

      - name: Use Node.js ${{ matrix.node-version }} # запуск Node.js
        uses: actions/setup-node@v3  # использование пакета Node.js
        with: # правила для пакета setup-node 
          node-version: ${{ matrix.node-version }} 
          cache: npm # кэширование npm,чтобы пакеты были в кэше для быстроты работы

      - name: Install Dependencies # установка npm
        run: | 
          npm install  

      - name: Build # сборка проекта
        run: |
          npm run build

      - name: Deploy # выгрузка проекта в git и сайта в интернет
        uses: JamesIves/github-pages-deploy-action@v4 # использование пакета
        with: #правила, из папки dist добавляет данные в ветку gh-pages
          branch: gh-pages 
          folder: dist 